apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJjSEp2Y0dWMGNtOTJZVzh0WTNSeWJEcG5hSEJmUmxZMGJIY3lkM05JYW05RE9VMTBTSG81ZEU1dWVsbFlkWFpVUlhveU1tTTBha3BMIn19fQ==
type: kubernetes.io/dockerconfigjson
