apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-service
  namespace: cinemaabyss
  labels:
    app: proxy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: proxy-service
    spec:
      containers:
      - name: proxy-service
        image: ghcr.io/propetrovao-ctrl/architecture-cinemaabyss/proxy-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: MONOLITH_URL
          valueFrom:
            configMapKeyRef:
              name: cinemaabyss-config
              key: MONOLITH_URL
        - name: MOVIES_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: cinemaabyss-config
              key: MOVIES_SERVICE_URL
        - name: EVENTS_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: cinemaabyss-config
              key: EVENTS_SERVICE_URL
        - name: GRADUAL_MIGRATION
          valueFrom:
            configMapKeyRef:
              name: cinemaabyss-config
              key: GRADUAL_MIGRATION
        - name: MOVIES_MIGRATION_PERCENT
          valueFrom:
            configMapKeyRef:
              name: cinemaabyss-config
              key: MOVIES_MIGRATION_PERCENT
        resources:
          limits:
            cpu: "300m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: cinemaabyss
spec:
  selector:
    app: proxy-service
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP

